/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishJarRouteImport } from './routes/wish-jar'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as GiftRouteImport } from './routes/gift'
import { Route as FeelingRouteImport } from './routes/feeling'
import { Route as BirthdayRouteImport } from './routes/birthday'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BirthdayDayRouteImport } from './routes/birthday_.$day'

const WishJarRoute = WishJarRouteImport.update({
  id: '/wish-jar',
  path: '/wish-jar',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftRoute = GiftRouteImport.update({
  id: '/gift',
  path: '/gift',
  getParentRoute: () => rootRouteImport,
} as any)
const FeelingRoute = FeelingRouteImport.update({
  id: '/feeling',
  path: '/feeling',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdayRoute = BirthdayRouteImport.update({
  id: '/birthday',
  path: '/birthday',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdayDayRoute = BirthdayDayRouteImport.update({
  id: '/birthday_/$day',
  path: '/birthday/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/birthday': typeof BirthdayRoute
  '/feeling': typeof FeelingRoute
  '/gift': typeof GiftRoute
  '/memories': typeof MemoriesRoute
  '/wish-jar': typeof WishJarRoute
  '/birthday/$day': typeof BirthdayDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/birthday': typeof BirthdayRoute
  '/feeling': typeof FeelingRoute
  '/gift': typeof GiftRoute
  '/memories': typeof MemoriesRoute
  '/wish-jar': typeof WishJarRoute
  '/birthday/$day': typeof BirthdayDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/birthday': typeof BirthdayRoute
  '/feeling': typeof FeelingRoute
  '/gift': typeof GiftRoute
  '/memories': typeof MemoriesRoute
  '/wish-jar': typeof WishJarRoute
  '/birthday_/$day': typeof BirthdayDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/birthday'
    | '/feeling'
    | '/gift'
    | '/memories'
    | '/wish-jar'
    | '/birthday/$day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/birthday'
    | '/feeling'
    | '/gift'
    | '/memories'
    | '/wish-jar'
    | '/birthday/$day'
  id:
    | '__root__'
    | '/'
    | '/birthday'
    | '/feeling'
    | '/gift'
    | '/memories'
    | '/wish-jar'
    | '/birthday_/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BirthdayRoute: typeof BirthdayRoute
  FeelingRoute: typeof FeelingRoute
  GiftRoute: typeof GiftRoute
  MemoriesRoute: typeof MemoriesRoute
  WishJarRoute: typeof WishJarRoute
  BirthdayDayRoute: typeof BirthdayDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wish-jar': {
      id: '/wish-jar'
      path: '/wish-jar'
      fullPath: '/wish-jar'
      preLoaderRoute: typeof WishJarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift': {
      id: '/gift'
      path: '/gift'
      fullPath: '/gift'
      preLoaderRoute: typeof GiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeling': {
      id: '/feeling'
      path: '/feeling'
      fullPath: '/feeling'
      preLoaderRoute: typeof FeelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthday': {
      id: '/birthday'
      path: '/birthday'
      fullPath: '/birthday'
      preLoaderRoute: typeof BirthdayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthday_/$day': {
      id: '/birthday_/$day'
      path: '/birthday/$day'
      fullPath: '/birthday/$day'
      preLoaderRoute: typeof BirthdayDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BirthdayRoute: BirthdayRoute,
  FeelingRoute: FeelingRoute,
  GiftRoute: GiftRoute,
  MemoriesRoute: MemoriesRoute,
  WishJarRoute: WishJarRoute,
  BirthdayDayRoute: BirthdayDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
